import { Bond } from "@/lib/types";

export const MOCK_BONDS: Bond[] = [
  {
    id: "b1",
    name: "CAFE2013",
    issuerId: "mock-issuer-1",
    issuerName: "Cafe Co.",
    sector: "Food & Beverage",
    description: "something",
    fullDescription: "US Treasury bonds are considered one of the safest investments globally, backed by the full faith and credit of the US government. This 10-year bond offers a stable return with minimal risk, making it ideal for conservative investors.",
    interestApyPct: 24,
    durationMonths: 6,
    collateral: "Other",
    fundedUsd: 0,
    targetUsd: 5000,
    maturityDate: new Date(Date.now() + 162 * 24 * 3600 * 1000).toISOString(),
    verified: true,
    status: "active",
    riskLevel: "Low Risk",
    rating: "AAA",
    couponRate: 8.0,
    paymentFrequency: "Semi-annual",
    faceValue: 1000,
    minInvestment: 50,
    available: 100000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "b2",
    name: "Cafe Bond 2025",
    issuerId: "mock-issuer-2",
    issuerName: "Equip",
    sector: "Equipment",
    description: "Equip",
    fullDescription: "Equipment financing bond for small business expansion. Secured by commercial kitchen equipment and backed by established revenue streams.",
    interestApyPct: 20,
    durationMonths: 12,
    collateral: "Other",
    fundedUsd: 0,
    targetUsd: 10000,
    maturityDate: new Date(Date.now() + 341 * 24 * 3600 * 1000).toISOString(),
    verified: true,
    status: "active",
    riskLevel: "Medium Risk",
    rating: "BBB",
    couponRate: 7.5,
    paymentFrequency: "Semi-annual",
    faceValue: 1000,
    minInvestment: 50,
    available: 100000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "b3",
    name: "Test Bond 2025",
    issuerId: "mock-issuer-3",
    issuerName: "Dev Co.",
    sector: "Software",
    description: "Test bond for development",
    fullDescription: "Software development financing for a growing tech startup. Secured by intellectual property and backed by a strong customer pipeline.",
    interestApyPct: 20,
    durationMonths: 12,
    collateral: "Other",
    fundedUsd: 0,
    targetUsd: 10000,
    maturityDate: new Date(Date.now() + 340 * 24 * 3600 * 1000).toISOString(),
    verified: true,
    status: "active",
    riskLevel: "Medium Risk",
    rating: "BBB",
    couponRate: 7.5,
    paymentFrequency: "Semi-annual",
    faceValue: 1000,
    minInvestment: 50,
    available: 100000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "b4",
    name: "Test Bond e18cecc2",
    issuerId: "mock-issuer-4",
    issuerName: "E2E test",
    sector: "QA",
    description: "E2E test",
    fullDescription: "Quality assurance testing bond for automated testing infrastructure expansion.",
    interestApyPct: 20,
    durationMonths: 12,
    collateral: "Other",
    fundedUsd: 0,
    targetUsd: 10000,
    maturityDate: new Date(Date.now() + 340 * 24 * 3600 * 1000).toISOString(),
    verified: true,
    status: "active",
    riskLevel: "Medium Risk",
    rating: "BBB",
    couponRate: 7.5,
    paymentFrequency: "Semi-annual",
    faceValue: 1000,
    minInvestment: 50,
    available: 100000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "b5",
    name: "Test Bond d91748d8",
    issuerId: "mock-issuer-5",
    issuerName: "E2E test",
    sector: "QA",
    description: "E2E test",
    fullDescription: "Quality assurance testing bond for automated testing infrastructure expansion.",
    interestApyPct: 20,
    durationMonths: 12,
    collateral: "Other",
    fundedUsd: 0,
    targetUsd: 10000,
    maturityDate: new Date(Date.now() + 342 * 24 * 3600 * 1000).toISOString(),
    verified: true,
    status: "active",
    riskLevel: "Medium Risk",
    rating: "BBB",
    couponRate: 7.5,
    paymentFrequency: "Semi-annual",
    faceValue: 1000,
    minInvestment: 50,
    available: 100000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "b6",
    name: "Test Bond b0709eb3",
    issuerId: "mock-issuer-6",
    issuerName: "E2E test",
    sector: "QA",
    description: "E2E test",
    fullDescription: "Quality assurance testing bond for automated testing infrastructure expansion.",
    interestApyPct: 20,
    durationMonths: 12,
    collateral: "Other",
    fundedUsd: 0,
    targetUsd: 10000,
    maturityDate: new Date(Date.now() + 343 * 24 * 3600 * 1000).toISOString(),
    verified: true,
    status: "active",
    riskLevel: "Medium Risk",
    rating: "BBB",
    couponRate: 7.5,
    paymentFrequency: "Semi-annual",
    faceValue: 1000,
    minInvestment: 50,
    available: 100000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];


